import { array, defineVisual, frame, mark, visual } from '../primitives.mjs';

const items = ['0', '1', '2', '3', '4', '5', '6'];
const batch = (start, end, extra = {}) => array(items, [
  mark(start, `start=${start}`, extra.result ? 'output' : 'focus', 'batch-start'),
  mark(Math.min(end - 1, items.length - 1), `last included=${Math.min(end - 1, items.length - 1)}`, 'state', 'batch-end'),
], {
  batchSize: '3',
  halfOpenSlice: `[${start}:${end}]`,
  ...extra,
});

const draft = visual('Advance one start cursor by batch size and yield the half-open slice; sequence slicing automatically clips the final end.', [
  frame('Validate the batch size', 'For items [0,1,2,3,4,5,6] and batch_size=3, the positive-size guard passes.', batch(0, 3, {
    guard: '3 > 0',
    nextStart: '0',
  }), 'validate'),
  frame('Yield the first half-open slice', 'start=0 yields items[0:3]=[0,1,2]. Index 3 is excluded.', batch(0, 3, {
    yielded: '[0,1,2]',
    coveredIndexes: '0,1,2',
  }), 'batch-zero'),
  frame('Advance start by exactly three', 'range advances start from 0 to 3, yielding items[3:6]=[3,4,5] with no overlap or gap.', batch(3, 6, {
    movement: 'start: 0 -> 3',
    yielded: '[3,4,5]',
    coveredIndexes: '3,4,5',
  }), 'batch-three'),
  frame('Clip the final slice at sequence end', 'The next start is 6. items[6:9] stops at len(items)=7, so it yields [6] rather than dropping the remainder.', batch(6, 9, {
    movement: 'start: 3 -> 6',
    effectiveEnd: 'min(9,7)=7',
    yielded: '[6]',
  }), 'batch-six'),
  frame('Stop at the next range boundary', 'The next candidate start 9 is not below len(items)=7, so range produces no further slice.', batch(6, 9, {
    stop: 'next start 9 >= 7',
    result: '[[0,1,2],[3,4,5],[6]]',
  }), 'stop'),
]);

const review = {
  pattern: 'Fixed-stride half-open slicing over a sequence.',
  recognitionCue: 'Use it when every item must appear once in consecutive batches and the final batch may be shorter than the requested size.',
  invariant: 'Before each yield, indexes below start have appeared exactly once; items[start:start+batch_size] contributes the next non-overlapping range, clipped only by sequence length.',
  stateModel: 'Retain the immutable items, positive batch_size, and current start generated by range; Python slicing supplies the effective end.',
  visualRationale: 'The full indexed input remains visible while stable start and included-end markers move by one batch, with half-open bounds and clipping arithmetic printed in every frame.',
  rejectedAlternatives: [
    'Reshaping requires divisibility or padding and does not match the final-short-batch contract.',
    'Dropping the last short slice loses valid examples.',
    'Showing only three output lists hides stride, half-open boundaries, and the positive-size guard.',
  ],
  transferLesson: 'Use half-open slices and a fixed stride to partition ordered data without overlap; let bounded slicing handle a short tail explicitly.',
  reviewStatus: 'reviewed',
};

export default defineVisual('mini-batches', draft, review);
